### ISSUE TITLE
refactor(turboServer): use environment variables for configuration

### ISSUE THREAD

**Issue by johnhooks** [felixmosh/turborepo-gh-artifacts#18]
The suggest way to initiate TurboRepo in CI seems to be to use environment variables:

Modified except from [Remote Caching](https://turbo.build/repo/docs/ci/github-actions#remote-caching) (I added `TURBO_REMOTE_ONLY`)

```yaml
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    # To use Turborepo Remote Caching, set the following environment variables for the job.
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      TURBO_REMOTE_ONLY: true
```

And it looks like they didn't document it but from what it looks like, TurboRepo might just use a `TURBO_API` environment variable... here is what I'm basing the idea on [reference](https://github.com/vercel/turbo/blob/658dcadceb227c815d9db0ebdf248e78daf65482/cli/internal/config/config_file.go#L196), I'll be testing this soon.

If I'm already using an environment variable for the `turbo` cli command in my workflow steps, is there any issue with modifying this as so... or even remove the `server-token` input?

```ts
// src/turboServer.ts line 16
const serverToken = process.env.TURBO_TOKEN || getInput(Inputs.SERVER_TOKEN, {
  required: true,
  trimWhitespace: true,
});
```

Then there isn't any need to pass `turbo` special arguments in CI. It should just use the remote caching server or fail.

If this works would you be interested in a PR?
