### ISSUE TITLE
Not getting a cache hit for some reason

### ISSUE THREAD

**Issue by moltar** [felixmosh/turborepo-gh-artifacts#2]
```
Run felixmosh/turborepo-gh-artifacts@v1
  with:
    repo-token: ***
    server-token: /home/runner/work/_temp/_runner_file_commands/add_path_54db2817-4e5b-4ad7-bc55-29ad818f363b
TURBO_LOCAL_SERVER_PID: 1904
```

---

```
npx turbo run build --api="http://127.0.0.1:9080/" --token="/home/runner/work/_temp/_runner_file_commands/add_path_213b4c67-ecc2-4ddc-911f-b8dc1f8abafe" --team="moltar" --scope="sub-project-1" --include-dependencies
```

---

```
sub-project-2:build: cache miss, executing 65c0a770b1950c86
```

---

```
Post job cleanup.
Found server pid: 1904
Killing server pid: 1904
There is nothing to upload.
Server logs:
Cache dir: /home/runner/work/_temp/turbo-cache
Local Turbo server is listening at http://127.0.0.1:9080/
Got a GET request /v8/artifacts/65c0a770b1950c86
Got a GET request /v8/artifacts/37e71657dbacff1d
Got a PUT request /v8/artifacts/65c0a770b1950c86
Got a PUT request /v8/artifacts/37e71657dbacff1d
```

Then if I re-run the workflow again, I get the same cache cache key `65c0a770b1950c86`, and yet still a miss.

Any ideas?

Project demo is here: https://github.com/moltar/projen-turborepo-test
