### ISSUE TITLE
context deadline exceeded (Client.Timeout exceeded while awaiting headers)

### ISSUE THREAD

**Issue by dstoyanoff** [felixmosh/turborepo-gh-artifacts#22]
Hello,
I am having trouble making this action work. After enabling turbo trace logs, I saw these errors:
```
2023-01-16T07:33:00.8209123Z 2023-01-16T07:33:00.820Z [ERROR] turbo: request failed: error="Get \"http://172.0.0.1:9080/v8/artifacts/48bf385e2de897f2?slug=magna\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)" method=GET url=http://172.0.0.1:9080/v8/artifacts/48bf385e2de897f2?slug=magna
```
Any clue what the issue might be?

**Comment by felixmosh** [comment]
Hi,
No I'm not familiar with this error... Maybe the local server didn't started? can you check its logs?

**Comment by dstoyanoff** [comment]
The actions logs this:
```
Run felixmosh/turborepo-gh-artifacts@v1
TURBO_LOCAL_SERVER_PID: 2486
Warning: The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-[11](https://github.com/magna-eng/web/actions/runs/3928155787/jobs/6715472911#step:6:12)-github-actions-deprecating-save-state-and-set-output-commands/
```

Then the post action logs look like this:
```
Post job cleanup.
Found server pid: [2](https://github.com/magna-eng/web/actions/runs/3928155787/jobs/6715472911#step:11:2)486
Killing server pid: 2486
There is nothing to upload.
Server logs:
Cache dir: /home/runner/work/_temp/turbo-cache
Local Turbo server is listening at http://12[7](https://github.com/magna-eng/web/actions/runs/3928155787/jobs/6715472911#step:11:7).0.0.1:9080
```

**Comment by felixmosh** [comment]
From the error looks like your local server not started, and Turborepo fails on timeout, is your setup is similar to this example?
https://github.com/felixmosh/turborepo-gh-artifacts-example

**Comment by dstoyanoff** [comment]
Yes, I had a look at that example. Here is part of the workflow:
```
      - name: TurboRepo local server
        uses: felixmosh/turborepo-gh-artifacts@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          server-token: ${{ env.TURBO_TOKEN }}

      - name: Build & Test
        run: npx turbo run build test --filter investor --api="http://172.0.0.1:9080" --token="${{ env.TURBO_TOKEN }}" --team=magna -vvv
```
