### ISSUE TITLE
Error: TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by moltar** [felixmosh/turborepo-gh-artifacts#3]
In the post step, getting the following:

```
Post job cleanup.
Found server pid: 1643
Killing server pid: 1643
Error: TypeError: Cannot read property 'map' of undefined
```

Sorry, doesn't provide any more info than that.

---

![screenshot-20220208T102136-SQSGOUx6](https://user-images.githubusercontent.com/491247/152911917-8cd25e3d-8050-4e95-b918-c0866b5b89b5.png)

**Comment by felixmosh** [comment]
Can you share the setup?

**Comment by moltar** [comment]
```yaml
# ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".

name: build
on:
  pull_request: {}
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      self_mutation_happened: ${{ steps.self_mutation.outputs.self_mutation_happened }}
    env:
      CI: "true"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Setup Node.js
        uses: actions/setup-node@v2.2.0
        with:
          cache: yarn
          cache-dependency-path: "**/yarn.lock"
      - name: Setup Node.js
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 14.17.0
      - name: Install dependencies
        run: yarn install --check-files
      - name: build
        run: npx projen build
      - id: self_mutation
        name: Find mutations
        run: |-
          git add .
          git diff --staged --patch --exit-code > .repo.patch || echo "::set-output name=self_mutation_happened::true"
      - if: steps.self_mutation.outputs.self_mutation_happened
        name: Upload patch
        uses: actions/upload-artifact@v2
        with:
          name: .repo.patch
          path: .repo.patch
      - name: Fail build on mutation
        if: steps.self_mutation.outputs.self_mutation_happened
        run: |-
          echo "::error::Files were changed during build (see build log). If this was triggered from a fork, you will need to update your branch."
          cat .repo.patch
          exit 1
      - name: Upload artifact
        uses: actions/upload-artifact@v2.1.1
        with:
          name: build-artifact
          path: dist
  self-mutation:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: always() && needs.build.outputs.self_mutation_happened && !(github.event.pull_request.head.repo.full_name != github.repository)
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PROJEN_GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Download patch
        uses: actions/download-artifact@v2
        with:
          name: .repo.patch
          path: ${{ runner.temp }}
      - name: Apply patch
        run: '[ -s ${{ runner.temp }}/.repo.patch ] && git apply ${{ runner.temp }}/.repo.patch || echo "Empty patch. Skipping."'
      - name: Set git identity
        run: |-
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
      - name: Push changes
        run: |2-
            git add .
            git commit -s -m "chore: self mutation"
            git push origin HEAD:${{ github.event.pull_request.head.ref }}
  turbo:
    name: build
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    if: "! needs.build.outputs.self_mutation_happened"
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifact
          path: dist
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup turbo cache
        uses: felixmosh/turborepo-gh-artifacts@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          server-token: ${{ github.sha }}
      - name: Setup Node.js
        uses: actions/setup-node@v2.2.0
        with:
          cache: yarn
          cache-dependency-path: "**/yarn.lock"
      - name: Setup Node.js
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 14.17.0
      - name: Install dependencies
        run: yarn install --check-files --frozen-lockfile
      - name: Build
        run: npx turbo run build --api="http://127.0.0.1:9080" --token="${{ github.sha }}" --team="${{ github.repository_owner }}" --scope="${{ matrix.scope }}" --include-dependencies
    strategy:
      fail-fast: true
      matrix:
        scope:
          - "@foo/backend"
          - "@foo/e2e"
          - "@foo/frontend"
          - "@foo/data-parser"
          - "@foo/openapi-spec"
```
