### ISSUE TITLE
How would this action work in a multi-job setup?

### ISSUE THREAD

**Issue by alexbjorlig** [felixmosh/turborepo-gh-artifacts#7]

**Comment by felixmosh** [comment]
Hi, thank you for opening this issue.
Can you elaborate what do you mean by "multi-job setup"?
Can you add a small config example?

**Comment by felixmosh** [comment]
Ping

**Comment by felixmosh** [comment]
ping?

**Comment by alexbjorlig** [comment]
I'm so sorry for not getting back to you - super busy with making Turborepo working on Github actions 😅  The example in the README.md shows an example with the artifacts running in the same github action job. My question was related to how this would look like, if the github actions contained multiple jobs - maybe even a matrix in some of the jobs.

But in the end we disabled remote artifacts with turborepo, and created an initial build step.

```
      - name: Turbo Cache
        id: turbo-cache
        uses: actions/cache@v3
        with:
          path: .turbo
          key: turbo-${{ github.ref_name }}-${{ github.sha }}
```
